### ISSUE TITLE
Review comments/issues VISSv2.x_PayloadEncoding.html

### ISSUE THREAD

**Issue by petervolvowinz** [COVESA/vehicle-information-service-specification#15]
**Status of This Document**

This document is merely a **W3C-internal document**. It has no official standing of any kind and does not represent consensus of the **W3C Membership**.

REPLACE with COVESA internal document.

**Protobuf encoding**

"Protobuf encoding serves as an **optimal** solution"  optimal as in really proven to be the optimal solution ? or is it merely an optimized solution, thus serves as an efficient solution ...

**Encoding and Decoding with Protobuf**

It could be noted that if multiple values are returned in some cases it is easier to have one or more values always returned as an array, otherwise the client needs to inspect the actual data type returned. But as mentioned this is out of scope for the spec.

**Comment by UlfBj** [comment]
With PR#20, this can be closed.
The encoding/decoding issue is addressed in implementation.
