### ISSUE TITLE
VSS explainer link in VISS-explainer.md corrupted

### ISSUE THREAD

**Issue by Herrmann-Alexander** [COVESA/vehicle-information-service-specification#26]
I just wanted to point out that the link in the VISS-explainer.md file pointing to the VSS explanation page is corrupted.
![VSS-link-corrupted](https://github.com/user-attachments/assets/36c782b9-c343-4260-8a8a-8a5258e0eb83)
![grafik](https://github.com/user-attachments/assets/9e1d4084-3303-467f-9e31-e2e4cd3ea875)

**Comment by petervolvowinz** [comment]
PR to fix this done.
