### ISSUE TITLE
Need for a license file

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle-information-service-specification#4]
Should we possibly have a license file in this repo, or at least be more specific on what licenses apply? We mention [something](https://github.com/COVESA/vehicle-information-service-specification/blob/main/spec/VISSv2_Core.html#L122) about copyright in the *.html files, but not much about licenses.

See:

- https://github.com/w3c/automotive/blob/gh-pages/LICENSE.md
- https://www.w3.org/copyright/software-license-2023/

**Comment by UlfBj** [comment]
MPL v2.0 added.
